# Generated by Django 4.1.3 on 2022-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("phone", models.CharField(max_length=10, verbose_name="Teléfono")),
                ("adress", models.CharField(max_length=200, verbose_name="Dirección")),
                (
                    "document",
                    models.CharField(max_length=15, verbose_name="Número de documento"),
                ),
            ],
        ),
    ]
