# Generated by Django 4.1.3 on 2022-11-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_equipos_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Equipos",
            new_name="Equipo",
        ),
    ]
