# Generated by Django 4.1.3 on 2022-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("ciudad", models.CharField(max_length=200, verbose_name="Nombre")),
                ("titulos", models.CharField(max_length=200, verbose_name="Nombre")),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
